-- =============================================================================
-- AuraGate — Initial Schema Migration
-- =============================================================================
-- This migration was auto-generated by drizzle-kit and then manually edited
-- to add PostgreSQL declarative partitioning on the usage_logs table.
--
-- Manual edits:
--   1. Added PARTITION BY RANGE (created_at) to usage_logs CREATE TABLE.
--   2. Added composite PRIMARY KEY (id, created_at) — required by PostgreSQL
--      because the partition key must be part of the PK.
--   3. Removed FK constraint on usage_logs.tenant_id — PostgreSQL does not
--      support foreign keys on partitioned tables. Referential integrity
--      is enforced at the application layer (BullMQ worker in Phase 5).
--   4. Added initial monthly partitions for current ± 6 months.
--      Future partitions are created by scripts/create-partitions.ts.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TENANTS — Multi-Tenant Organization Registry
-- ---------------------------------------------------------------------------
CREATE TABLE "tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"budget_usd" numeric(19, 4) DEFAULT '0.0000' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenants_name_unique" UNIQUE("name")
);

--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- API_KEYS — Hashed API Key Registry
-- ---------------------------------------------------------------------------
CREATE TABLE "api_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"key_hash" varchar(64) NOT NULL,
	"description" varchar(255),
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "api_keys_key_hash_unique" UNIQUE("key_hash")
);

--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- USAGE_LOGS — Time-Partitioned Telemetry Ledger
-- ---------------------------------------------------------------------------
-- IMPORTANT: This table uses PARTITION BY RANGE on created_at.
-- PostgreSQL requires the partition key to be part of the primary key,
-- hence the composite PK (id, created_at).
--
-- Foreign keys are NOT supported on partitioned tables in PostgreSQL.
-- Referential integrity for tenant_id is enforced at the application layer.
-- ---------------------------------------------------------------------------
CREATE TABLE "usage_logs" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"request_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"provider" varchar(50) NOT NULL,
	"model" varchar(100) NOT NULL,
	"latency_ms" integer DEFAULT 0 NOT NULL,
	"prompt_tokens" integer DEFAULT 0 NOT NULL,
	"completion_tokens" integer DEFAULT 0 NOT NULL,
	"cost_usd" numeric(19, 4) DEFAULT '0.0000' NOT NULL,
	"cache_hit" boolean DEFAULT false NOT NULL,
	"failover_used" boolean DEFAULT false NOT NULL,
	"provider_status_code" integer,
	"status" varchar(20) DEFAULT 'SUCCESS' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	PRIMARY KEY ("id", "created_at")
) PARTITION BY RANGE ("created_at");

--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Foreign Keys
-- ---------------------------------------------------------------------------
-- Note: usage_logs FK is intentionally omitted (not supported on partitioned tables)
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_tenant_id_tenants_id_fk"
  FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id")
  ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
-- Composite index for dashboard queries: "all usage for tenant X, newest first"
-- This index is created on the parent table and automatically inherited by partitions.
CREATE INDEX "idx_usage_logs_tenant_created"
  ON "usage_logs" USING btree ("tenant_id", "created_at" DESC);

--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Initial Monthly Partitions
-- ---------------------------------------------------------------------------
-- These cover the current period. Future partitions should be created via:
--   npx tsx scripts/create-partitions.ts --months-ahead 12
--
-- The partition-manager script uses IF NOT EXISTS, so re-running is safe.
-- Partitions here are a bootstrap — the script handles ongoing maintenance.
-- ---------------------------------------------------------------------------